import { RouteMap } from '@/src/components/RouteMap';
import { Button, Metric, Progress } from '@/src/components/UI';
import { formatDuration, nextCheckpoint, paceMinutesPerKm, routeProgress, xpForActivity } from '@/src/domain/engine';
import { useApp } from '@/src/state/AppContext';
import { palette, radius } from '@/src/theme';
import { useRouter } from 'expo-router';
import { useEffect } from 'react';
import { Pressable, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

export default function ActivityScreen(){const router=useRouter(),{width}=useWindowDimensions(),wide=width>=800;const {journey,session,tick,togglePause,finishSession,lastRewardXp,homeArea}=useApp();
 useEffect(()=>{const timer=setInterval(tick,1000);return()=>clearInterval(timer)},[tick]);
 useEffect(()=>{if(session.status==='idle')router.replace('/')},[router,session.status]);
 if(session.status==='idle')return null;
 const total=journey.completedKm+session.distanceKm,progress=routeProgress(total,journey.distanceKm),next=nextCheckpoint(journey.checkpoints,total);
 const close=()=>{if(session.status==='active')togglePause();router.back()};
 if(session.status==='complete')return <SafeAreaView style={styles.complete}><Text style={styles.doneIcon}>✓</Text><Text style={styles.doneTitle}>Session complete</Text><Text style={styles.doneSub}>Every stride moved you through the world.</Text><View style={styles.summary}><Metric label="Distance" value={`${session.distanceKm.toFixed(2)} km`}/><Metric label="Time" value={formatDuration(session.elapsedSeconds)}/><Metric label="XP earned" value={`+${lastRewardXp}`} accent/></View><Text style={styles.verify}>◷ Pending server verification</Text><Button title="Back to dashboard" onPress={()=>router.replace('/')}/></SafeAreaView>;
 return <SafeAreaView style={styles.safe}><View style={styles.top}><Pressable onPress={close} accessibilityRole="button" accessibilityLabel="Pause and close activity"><Text style={styles.close}>×</Text></Pressable><View><Text style={styles.live}>{session.status==='paused'?'PAUSED':'● LIVE'} · {session.type.toUpperCase()}</Text><Text style={styles.route}>{journey.title}</Text></View><Text style={styles.time}>{formatDuration(session.elapsedSeconds)}</Text></View><View style={[styles.main,wide&&styles.wide]}><View style={styles.map}><RouteMap journey={journey} progress={progress} homeAreaLabel={homeArea?.label}/></View><View style={styles.panel}><Text style={styles.distance}>{session.distanceKm.toFixed(2)}<Text style={styles.unit}> km</Text></Text><Text style={styles.label}>SESSION DISTANCE</Text><View style={styles.metrics}><Metric label="Pace / km" value={paceMinutesPerKm(session.distanceKm,session.elapsedSeconds)}/><Metric label="XP earned" value={`+${xpForActivity(session.distanceKm)}`} accent/><Metric label="Route" value={`${Math.round(progress*100)}%`}/></View><View style={styles.checkpoint}><Text style={styles.pin}>⌖</Text><View style={{flex:1}}><Text style={styles.label}>NEXT CHECKPOINT</Text><Text style={styles.next}>{next?.name??'Finish line'}</Text></View><Text style={styles.remaining}>{Math.max(0,(next?.distanceKm??journey.distanceKm)-total).toFixed(1)} km</Text></View><Progress value={progress} color={palette.accent} height={10}/><View style={styles.controls}><Button title={session.status==='paused'?'Resume':'Pause'} icon={session.status==='paused'?'▶':'Ⅱ'} variant="secondary" onPress={togglePause}/><Button title="Finish" icon="■" onPress={finishSession}/></View><Text style={styles.demo}>Demo mode simulates {session.type==='run'?'10.8':'5.8'} km/h. Connect a verified device in Settings.</Text></View></View></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:palette.ink},top:{height:72,flexDirection:'row',alignItems:'center',paddingHorizontal:16,gap:14},close:{color:palette.text,fontSize:32,width:32},live:{color:palette.lime,fontSize:10,fontWeight:'900',letterSpacing:1},route:{color:palette.text,fontSize:14,fontWeight:'800',marginTop:3},time:{marginLeft:'auto',color:palette.text,fontFamily:'SpaceMono',fontSize:17},main:{flex:1,gap:12,padding:12},wide:{flexDirection:'row'},map:{flex:1.4,minHeight:260},panel:{flex:1,backgroundColor:palette.surface,borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,padding:20,gap:18,justifyContent:'center'},distance:{color:palette.text,fontSize:52,fontWeight:'900',letterSpacing:-2},unit:{fontSize:20,color:palette.muted},label:{color:palette.muted,fontSize:10,fontWeight:'800',letterSpacing:1},metrics:{flexDirection:'row',gap:12},checkpoint:{flexDirection:'row',alignItems:'center',gap:12,backgroundColor:palette.elevated,padding:14,borderRadius:radius.md},pin:{color:palette.accent,fontSize:26},next:{color:palette.text,fontWeight:'800',marginTop:4},remaining:{color:palette.accent,fontWeight:'900'},controls:{flexDirection:'row',gap:10},demo:{color:palette.muted,fontSize:9,textAlign:'center'},complete:{flex:1,backgroundColor:palette.ink,padding:28,alignItems:'center',justifyContent:'center',gap:20},doneIcon:{fontSize:42,color:palette.ink,backgroundColor:palette.lime,width:78,height:78,borderRadius:39,textAlign:'center',lineHeight:78,fontWeight:'900'},doneTitle:{color:palette.text,fontSize:31,fontWeight:'900'},doneSub:{color:palette.muted,textAlign:'center'},summary:{width:'100%',maxWidth:560,flexDirection:'row',backgroundColor:palette.surface,borderRadius:radius.lg,padding:20,gap:12},verify:{color:palette.warning,fontSize:11,fontWeight:'700'}});
