import { Button, Card, Header, Progress, Screen } from '@/src/components/UI';
import { useApp } from '@/src/state/AppContext';
import { palette } from '@/src/theme';
import { useLocalSearchParams } from 'expo-router';
import { StyleSheet, Text, View } from 'react-native';

type Feature = { title: string; eyebrow: string; description: string; items: Array<[string, string, string]>; action?: string };
const features: Record<string, Feature> = {
  friends: { title:'Friends', eyebrow:'MOVE TOGETHER', description:'Compare progress without exposing anyone’s physical location.', items:[['Maya Chen','86.2 km this month','31 day streak'],['Omar Khan','74.8 km this month','18 day streak'],['Sofia Rossi','69.4 km this month','22 day streak']], action:'Invite a friend' },
  groups: { title:'Groups', eyebrow:'YOUR COMMUNITY', description:'Private spaces for families, teams, and fitness communities.', items:[['Stride Squad','12 members','You rank #3'],['Microsoft Movers','48 members','August 50K active'],['Weekend Walkers','8 members','Next walk Sunday']], action:'Create a group' },
  achievements: { title:'Achievements', eyebrow:'KEEP EXPLORING', description:'Milestones earned through verified movement and journey progress.', items:[['City Explorer','10 landmarks discovered','+500 XP'],['100 KM Club','Move 100 kilometres','Completed'],['Top 25','Reach your city’s top 25','Completed'],['Journey Maker','Complete three journeys','2 / 3']], action:'Share achievements' },
  history: { title:'Activity history', eyebrow:'YOUR MOVEMENT', description:'Recent sessions synchronize here after validation.', items:[['Dubai Marina Walk','Today · 32 min','3.1 km'],['Central Park Run','Friday · 48 min','7.6 km'],['Evening Walking Pad','Thursday · 25 min','2.2 km']] },
  notifications: { title:'Notifications', eyebrow:'STAY MOTIVATED', description:'Important progress without distracting noise.', items:[['Checkpoint reached','You arrived at Marina Walk','Today'],['Leaderboard update','You climbed four city positions','Yesterday'],['Streak reminder','Move today to keep your 12-day streak','Enabled']], action:'Notification preferences' },
  integrations: { title:'Devices & health', eyebrow:'CONNECTED MOVEMENT', description:'The MVP uses simulation. Production adapters remain isolated from map and journey logic.', items:[['Apple Health','Not connected','iOS'],['Health Connect','Not connected','Android'],['Bluetooth fitness device','No device paired','Treadmill · walking pad']], action:'Connect a device' },
  privacy: { title:'Privacy & data', eyebrow:'YOU ARE IN CONTROL', description:'Precise location is private by default. Competitive ranks use server-validated activity.', items:[['Physical location','Never shared publicly','Protected'],['Virtual route presence','Off','Private'],['Activity visibility','Friends only','Customizable'],['Data export & deletion','Available on request','Account control']], action:'Review consent' },
};

export default function FeatureScreen(){const {slug}=useLocalSearchParams<{slug:string}>();const {completedSessions}=useApp();const feature=features[slug]??features.privacy;const items=slug==='history'&&completedSessions.length?completedSessions.map(session=>[`${session.type==='run'?'Run':'Walk'} session`,`${Math.floor(session.elapsedSeconds/60)} min · ${session.verification}`,`${session.distanceKm.toFixed(2)} km`] as [string,string,string]):feature.items;return <Screen><Header eyebrow={feature.eyebrow} title={feature.title}/><Text style={styles.description}>{feature.description}</Text>{slug==='achievements'?<Progress value={.72} color={palette.warning}/>:null}<View style={styles.list}>{items.map(([title,subtitle,meta],index)=><Card key={`${title}-${index}`} style={styles.item}><View style={styles.badge}><Text style={styles.badgeText}>{index+1}</Text></View><View style={{flex:1}}><Text style={styles.title}>{title}</Text><Text style={styles.subtitle}>{subtitle}</Text></View><Text style={styles.meta}>{meta}</Text></Card>)}</View>{feature.action?<Button title={feature.action} variant="secondary"/>:null}<Text style={styles.note}>Connected production actions require authentication and backend services; this preview keeps them safely disabled.</Text></Screen>}
const styles=StyleSheet.create({description:{color:palette.muted,fontSize:14,lineHeight:21,maxWidth:600},list:{gap:10},item:{flexDirection:'row',alignItems:'center',gap:12},badge:{width:38,height:38,borderRadius:19,backgroundColor:palette.elevated,alignItems:'center',justifyContent:'center'},badgeText:{color:palette.accent,fontWeight:'900'},title:{color:palette.text,fontWeight:'800'},subtitle:{color:palette.muted,fontSize:11,marginTop:4},meta:{color:palette.lime,fontSize:10,fontWeight:'800',maxWidth:100,textAlign:'right'},note:{color:palette.muted,fontSize:9,lineHeight:14,textAlign:'center',marginTop:8}});
