import { Card, Chip, Header, Screen } from '@/src/components/UI';
import { leaderboard } from '@/src/data/mock';
import type { LeaderboardScope } from '@/src/domain/models';
import { palette } from '@/src/theme';
import { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';

const scopes:LeaderboardScope[]=['Global','Country','City','Friends','Group'];
const scopeData:Record<LeaderboardScope,{rank:number;factor:number}>={Global:{rank:842,factor:1.7},Country:{rank:94,factor:1.35},City:{rank:18,factor:1},Friends:{rank:4,factor:.72},Group:{rank:3,factor:.58}};
export default function LeaderboardScreen(){const [scope,setScope]=useState<LeaderboardScope>('City');const config=scopeData[scope];const entries=leaderboard.map(entry=>({...entry,rank:entry.isCurrentUser?config.rank:entry.id==='19'?config.rank+1:entry.rank,distanceKm:entry.distanceKm*config.factor}));return <Screen><Header eyebrow="AUGUST · DISTANCE" title="Leaderboard"/><View style={styles.scopes}>{scopes.map(s=><Chip key={s} label={s} selected={s===scope} onPress={()=>setScope(s)}/>)}</View><Card style={styles.you}><Text style={styles.youLabel}>YOUR {scope.toUpperCase()} RANK</Text><View style={styles.row}><Text style={styles.rank}>#{config.rank}</Text><View><Text style={styles.white}>Alex Morgan</Text><Text style={styles.muted}>68.7 km · 12 day streak</Text></View><Text style={styles.up}>↑ 4</Text></View></Card>{entries.map(entry=><View key={entry.id} style={[styles.entry,entry.isCurrentUser&&styles.current]}><Text style={styles.number}>{entry.rank}</Text><View style={[styles.avatar,entry.isCurrentUser&&{backgroundColor:palette.accent}]}><Text style={styles.initials}>{entry.initials}</Text></View><View style={{flex:1}}><Text style={styles.white}>{entry.name} {entry.verification==='verified'?'✓':''}</Text><Text style={styles.muted}>{entry.streak} day streak</Text></View><View style={styles.right}><Text style={styles.distance}>{entry.distanceKm.toFixed(1)} km</Text><Text style={styles.muted}>{entry.xp.toLocaleString()} XP</Text></View></View>)}<Text style={styles.note}>Competitive ranks include server-verified activity only.</Text></Screen>}
const styles=StyleSheet.create({scopes:{flexDirection:'row',gap:8,flexWrap:'wrap'},you:{backgroundColor:'#1A2B32',borderColor:palette.lime,gap:10},youLabel:{color:palette.lime,fontSize:10,fontWeight:'900',letterSpacing:1},row:{flexDirection:'row',alignItems:'center',gap:14},rank:{color:palette.lime,fontSize:32,fontWeight:'900'},white:{color:palette.text,fontWeight:'800'},muted:{color:palette.muted,fontSize:11,marginTop:3},up:{marginLeft:'auto',color:palette.lime,fontWeight:'900'},entry:{minHeight:72,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:palette.line,paddingHorizontal:10},current:{backgroundColor:`${palette.accent}12`,borderRadius:14,borderBottomWidth:0},number:{color:palette.muted,width:26,textAlign:'center',fontWeight:'800'},avatar:{width:42,height:42,borderRadius:21,backgroundColor:palette.elevated,alignItems:'center',justifyContent:'center'},initials:{color:palette.text,fontSize:11,fontWeight:'900'},right:{alignItems:'flex-end'},distance:{color:palette.text,fontWeight:'900'},note:{color:palette.muted,textAlign:'center',fontSize:10,marginTop:8}});
