import { RouteMap } from '@/src/components/RouteMap';
import { Button, Card, Header, Progress, Screen, SectionTitle } from '@/src/components/UI';
import { journeys } from '@/src/data/mock';
import { useApp } from '@/src/state/AppContext';
import { palette } from '@/src/theme';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { StyleSheet, Text, View } from 'react-native';

export default function JourneyDetail(){const {id}=useLocalSearchParams<{id:string}>(),router=useRouter(),{journey:activeJourney,selectJourney,startSession}=useApp();const baseJourney=journeys.find(j=>j.id===id);const journey=baseJourney?.id===activeJourney.id?activeJourney:baseJourney;if(!journey)return <Screen><Header eyebrow="NOT FOUND" title="Journey unavailable"/><Text style={styles.subtitle}>This journey may have been removed or the link is invalid.</Text><Button title="Go back" variant="secondary" onPress={()=>router.back()}/></Screen>;const progress=journey.completedKm/journey.distanceKm;const start=()=>{selectJourney(journey);startSession('walk');router.push('/activity')};return <Screen><Header eyebrow={journey.difficulty} title={journey.title}/><Text style={styles.subtitle}>{journey.subtitle} · {journey.city}</Text><RouteMap journey={journey} progress={progress}/><Card style={styles.stats}><View><Text style={styles.value}>{journey.distanceKm} km</Text><Text style={styles.label}>TOTAL DISTANCE</Text></View><View><Text style={styles.value}>{journey.checkpoints.length}</Text><Text style={styles.label}>LANDMARKS</Text></View><View><Text style={[styles.value,{color:palette.lime}]}>+{journey.rewardXp}</Text><Text style={styles.label}>COMPLETION XP</Text></View></Card><Progress value={progress} color={journey.color}/><Button title={journey.completedKm?'Continue journey':'Start journey'} icon="▶" onPress={start}/><SectionTitle title="Route highlights"/>{journey.checkpoints.map((c,i)=><Card key={c.id} style={styles.point}><View style={[styles.index,{backgroundColor:journey.color}]}><Text style={styles.indexText}>{i+1}</Text></View><View><Text style={styles.name}>{c.name}</Text><Text style={styles.subtitle}>{c.kind} · {c.distanceKm} km</Text></View></Card>)}</Screen>}
const styles=StyleSheet.create({subtitle:{color:palette.muted,fontSize:12,textTransform:'capitalize'},stats:{flexDirection:'row',justifyContent:'space-between',gap:12},value:{color:palette.text,fontSize:19,fontWeight:'900'},label:{color:palette.muted,fontSize:9,marginTop:4},point:{flexDirection:'row',alignItems:'center',gap:12},index:{width:34,height:34,borderRadius:17,alignItems:'center',justifyContent:'center'},indexText:{color:palette.ink,fontWeight:'900'},name:{color:palette.text,fontWeight:'800'}});
