import { Button, Card, Header, Progress, Screen, SectionTitle } from '@/src/components/UI';
import { challenges, leaderboard } from '@/src/data/mock';
import { palette } from '@/src/theme';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default function ChallengeDetail(){const {id}=useLocalSearchParams<{id:string}>();const router=useRouter();const [joined,setJoined]=useState(true);const challenge=challenges.find(c=>c.id===id);if(!challenge)return <Screen><Header eyebrow="NOT FOUND" title="Challenge unavailable"/><Text style={styles.desc}>This challenge may have ended or the link is invalid.</Text><Button title="Go back" variant="secondary" onPress={()=>router.back()}/></Screen>;return <Screen><Header eyebrow={`ENDS IN ${challenge.endsIn.toUpperCase()}`} title={challenge.title}/><Card style={styles.hero}><Text style={[styles.icon,{color:challenge.color}]}>◆</Text><Text style={styles.desc}>{challenge.description}</Text><Text style={styles.big}>{challenge.progress}<Text style={styles.unit}> / {challenge.target} {challenge.unit}</Text></Text><Progress value={challenge.progress/challenge.target} color={challenge.color} height={11}/><Text style={styles.meta}>{Math.round(challenge.progress/challenge.target*100)}% complete · +{challenge.rewardXp} XP reward</Text></Card><Button title={joined?'Challenge joined':'Join challenge'} icon={joined?'✓':'+'} variant={joined?'secondary':'primary'} onPress={()=>setJoined(value=>!value)}/><SectionTitle title="Top challengers"/>{leaderboard.slice(0,3).map(e=><View key={e.id} style={styles.row}><Text style={styles.rank}>#{e.rank}</Text><View style={styles.avatar}><Text style={styles.initials}>{e.initials}</Text></View><Text style={styles.name}>{e.name}</Text><Text style={styles.distance}>{e.distanceKm} km</Text></View>)}<Card><Text style={styles.name}>Activity verification</Text><Text style={styles.desc}>Only server-validated walking and running activity counts toward competitive rankings. A suspicious signal triggers review, not automatic punishment.</Text></Card></Screen>}
const styles=StyleSheet.create({hero:{alignItems:'center',gap:15,paddingVertical:28},icon:{fontSize:58},desc:{color:palette.muted,fontSize:13,lineHeight:20,textAlign:'center'},big:{color:palette.text,fontSize:40,fontWeight:'900'},unit:{fontSize:16,color:palette.muted},meta:{color:palette.muted,fontSize:11},row:{flexDirection:'row',alignItems:'center',gap:12,minHeight:62,borderBottomColor:palette.line,borderBottomWidth:1},rank:{color:palette.muted,width:28},avatar:{width:38,height:38,borderRadius:19,backgroundColor:palette.elevated,alignItems:'center',justifyContent:'center'},initials:{color:palette.text,fontSize:10,fontWeight:'900'},name:{color:palette.text,fontWeight:'800',flex:1},distance:{color:palette.lime,fontWeight:'900'}});
